using System;
using System.Collections.Generic;
using UnityEngine;

public class CardadoCardActionDevelopmentOverlayV2 : MonoBehaviour
{
    enum Step { None,Cards,DieAfterSkip,ArtistDie,SoldierTarget,SoldierDie,CollectorTarget,CollectorCard,BodyguardDie,MirrorTarget,MirrorOwnDie,MirrorTargetDie,ModifierDirection,ModifierTarget,ExecutionerTarget,ExecutionerEffects,SpecialArtistChoice,SpecialArtistDie,SpecialSoldierChoice,SpecialSoldierTarget,SpecialSoldierDie,SpecialSoldierAllDie,SpecialCollectorChoice,SpecialCollectorTake,SpecialCollectorPlay,SpecialBodyguardChoice,SpecialBodyguardTarget,SpecialMirrorChoice,SpecialMirrorTarget,SpecialMirrorOwnDie,SpecialMirrorTargetDie,SpecialMirrorFirstOpponent,SpecialMirrorFirstDie,SpecialMirrorSecondOpponent,SpecialMirrorSecondDie,SpecialExecutionerTarget,JokerTarget,JokerDie,GordonChoice }
    enum EffectType { Modifier,BodyguardDie,SpecialBodyguardPlayer,SpecialBodyguardHand }
    class Effect { public EffectType type; public CardInstance card; public int owner,target=-1,die=-1; public string key; }

    CardadoGameManager gm; Step step; bool visible; int pi=-1,ti=-1,si=-1,di=-1,mod;
    int trackedHand=-1,collectorPos; CardInstance active; string execMsg;
    readonly HashSet<int> blocked=new HashSet<int>(), playedCard=new HashSet<int>(), protectedPlayers=new HashSet<int>();
    readonly HashSet<string> protectedDice=new HashSet<string>(), playedDice=new HashSet<string>();
    readonly Dictionary<string,int> modifierOriginal=new Dictionary<string,int>();
    readonly List<Effect> effects=new List<Effect>(), execEffects=new List<Effect>();
    readonly List<int> collectorOpp=new List<int>(); readonly List<CardInstance> collectorPool=new List<CardInstance>();
    bool handBodyguard; Effect handBodyguardEffect;
    GUIStyle box,title,button,value,green,red,small;

    void Awake(){gm=GetComponent<CardadoGameManager>();if(gm==null)gm=FindFirstObjectByType<CardadoGameManager>();}
    void OnEnable(){if(gm==null)gm=FindFirstObjectByType<CardadoGameManager>();if(gm==null)return;gm.CardActionRequested+=CardRequested;gm.HandTurnStarted+=HandStarted;gm.DiePlayed+=DiePlayed;gm.RoundResolutionCompleted+=RoundEnded;}
    void OnDisable(){if(gm==null)return;gm.CardActionRequested-=CardRequested;gm.HandTurnStarted-=HandStarted;gm.DiePlayed-=DiePlayed;gm.RoundResolutionCompleted-=RoundEnded;}

    void CardRequested(CardadoPlayerState p,CardadoCardActionRequestType req){pi=Index(p);if(pi<0)return;visible=true;ti=si=di=-1;mod=0;active=null;execMsg=null;step=req==CardadoCardActionRequestType.ChooseArtistDie?Step.ArtistDie:Step.Cards;if(step==Step.Cards&&(p.hand.cardsInHand.Count==0||blocked.Contains(pi))){visible=false;step=Step.None;gm.TrySkipCardAction(pi);return;}}
    void HandStarted(CardadoPlayerState p,int hand,int starter){if(hand!=trackedHand){trackedHand=hand;blocked.Clear();playedCard.Clear();playedDice.Clear();ClearHandBodyguard();}visible=false;step=Step.None;pi=ti=si=di=-1;active=null;collectorOpp.Clear();collectorPool.Clear();}
    void DiePlayed(CardadoPlayerState p,int d,int v){int x=Index(p);string k=Key(x,d);playedDice.Add(k);if(modifierOriginal.ContainsKey(k)){modifierOriginal.Remove(k);RemoveEffect(EffectType.Modifier,k,true);}if(protectedDice.Remove(k))RemoveEffect(EffectType.BodyguardDie,k,true);}
    void ClearHandBodyguard(){if(handBodyguardEffect!=null)RemoveEffectObj(handBodyguardEffect,true);handBodyguardEffect=null;handBodyguard=false;}
    void RoundEnded(){for(int i=effects.Count-1;i>=0;i--)RemoveEffectObj(effects[i],true);effects.Clear();protectedPlayers.Clear();protectedDice.Clear();modifierOriginal.Clear();handBodyguardEffect=null;handBodyguard=false;playedDice.Clear();}

    void OnGUI(){if(gm==null)return;Styles();if(effects.Count>0)DrawEffects();if(!visible||pi<0)return;switch(step){
        case Step.Cards:Cards();break;case Step.DieAfterSkip:Dice("CHOOSE DIE","You skipped the card. You can still go back.",pi);break;case Step.ArtistDie:Dice("ARTIST","Choose one of your dice to reroll.",pi);break;
        case Step.SoldierTarget:Targets("SOLDIER","Choose an opponent.",false,false,Step.Cards);break;case Step.SoldierDie:Dice("SOLDIER","Choose a die from "+gm.Players[ti].playerId,ti);break;
        case Step.CollectorTarget:Targets("COLLECTOR","Choose an opponent.",false,false,Step.Cards);break;case Step.CollectorCard:CollectorCards();break;case Step.BodyguardDie:Dice("BODYGUARD","Choose one of your dice to protect.",pi);break;
        case Step.MirrorTarget:Targets("MIRROR","Choose an opponent.",false,false,Step.Cards);break;case Step.MirrorOwnDie:Dice("MIRROR","Choose your die.",pi);break;case Step.MirrorTargetDie:Dice("MIRROR","Choose "+gm.Players[ti].playerId+"'s die.",ti);break;
        case Step.ModifierDirection:ModifierDirection();break;case Step.ModifierTarget:ModifierTarget();break;case Step.ExecutionerTarget:Targets("EXECUTIONER",execMsg??"Choose an opponent.",false,true,Step.Cards);break;case Step.ExecutionerEffects:ExecutionerEffects();break;
        case Step.SpecialArtistChoice:Choice("SPECIAL ARTIST",new[]{"REROLL ONE DIE 3 TIMES","REROLL ALL YOUR DICE ONCE"},ChooseSpecialArtist,Step.Cards);break;case Step.SpecialArtistDie:Dice("SPECIAL ARTIST","Choose one die. It will be rerolled three times.",pi);break;
        case Step.SpecialSoldierChoice:Choice("SPECIAL SOLDIER",new[]{"ONE OPPONENT REROLLS ALL DICE","ALL OPPONENTS REROLL ONE DIE"},ChooseSpecialSoldier,Step.Cards);break;case Step.SpecialSoldierTarget:Targets("SPECIAL SOLDIER","Choose the opponent.",false,false,Step.SpecialSoldierChoice);break;case Step.SpecialSoldierDie:Dice("SPECIAL SOLDIER","Choose a die from "+gm.Players[ti].playerId,ti);break;case Step.SpecialSoldierAllDie:SpecialSoldierAll();break;
        case Step.SpecialCollectorChoice:Choice("SPECIAL COLLECTOR",new[]{"TAKE ONE CARD FROM EACH PLAYER","DRAW 3 CARDS"},ChooseSpecialCollector,Step.Cards);break;case Step.SpecialCollectorTake:SpecialCollectorTake();break;case Step.SpecialCollectorPlay:SpecialCollectorPlay();break;
        case Step.SpecialBodyguardChoice:Choice("SPECIAL BODYGUARD",new[]{"PROTECT ALL DICE OF ONE PLAYER","PROTECT ALL DICE PLAYED THIS HAND"},ChooseSpecialBodyguard,Step.Cards);break;case Step.SpecialBodyguardTarget:Targets("SPECIAL BODYGUARD","Choose the player to protect.",true,true,Step.SpecialBodyguardChoice);break;
        case Step.SpecialMirrorChoice:Choice("SPECIAL MIRROR",new[]{"EXCHANGE YOUR DIE WITH AN OPPONENT","EXCHANGE TWO OPPONENTS' DICE"},ChooseSpecialMirror,Step.Cards);break;case Step.SpecialMirrorTarget:Targets("SPECIAL MIRROR","Choose an opponent.",false,false,Step.SpecialMirrorChoice);break;case Step.SpecialMirrorOwnDie:Dice("SPECIAL MIRROR","Choose your die.",pi);break;case Step.SpecialMirrorTargetDie:Dice("SPECIAL MIRROR","Choose "+gm.Players[ti].playerId+"'s die.",ti);break;
        case Step.SpecialMirrorFirstOpponent:Pair("SPECIAL MIRROR","Choose the first opponent.",true);break;case Step.SpecialMirrorFirstDie:Dice("SPECIAL MIRROR","Choose "+gm.Players[ti].playerId+"'s die.",ti);break;case Step.SpecialMirrorSecondOpponent:Pair("SPECIAL MIRROR","Choose the second opponent.",false);break;case Step.SpecialMirrorSecondDie:Dice("SPECIAL MIRROR","Choose "+gm.Players[si].playerId+"'s die.",si);break;
        case Step.SpecialExecutionerTarget:Targets("SPECIAL EXECUTIONER","Choose a player who must discard their entire hand.",false,true,Step.Cards);break;case Step.JokerTarget:Targets("JOKER","Choose whose die to flip.",true,false,Step.Cards);break;case Step.JokerDie:Dice("JOKER","Choose the die to flip.",ti);break;case Step.GordonChoice:Choice("GORDON ROBLEYS",new[]{"SPECIAL ARTIST","SPECIAL SOLDIER","SPECIAL COLLECTOR","SPECIAL BODYGUARD"},ChooseGordon,Step.Cards);break;
    }}

    void Cards(){CardadoPlayerState p=gm.Players[pi];Rect r=Box(900,430);GUI.Box(r,"",box);GUI.Label(new Rect(r.x+20,r.y+20,860,45),p.playerId+" — CARD ACTION",title);GUI.Label(new Rect(r.x+20,r.y+70,860,30),"Play a card before choosing a die, or skip.",GUI.skin.label);float bw=145,g=12,total=p.hand.cardsInHand.Count*bw+Mathf.Max(0,p.hand.cardsInHand.Count-1)*g,x=r.x+(900-total)/2f;for(int i=0;i<p.hand.cardsInHand.Count;i++){var c=p.hand.cardsInHand[i];if(c==null||c.data==null)continue;if(GUI.Button(new Rect(x+i*(bw+g),r.y+120,bw,90),c.data.id+"\n"+c.data.cardType+(c.data.isBlankCard?"\nBlank":""),button))Select(c);}if(GUI.Button(new Rect(r.x+20,r.y+320,860,55),"SKIP CARD ACTION",button))Skip();}
    void Dice(string head,string text,int p){if(p<0||p>=gm.Players.Count)return;var s=gm.Players[p];Rect r=Box(760,390);GUI.Box(r,"",box);GUI.Label(new Rect(r.x+20,r.y+20,720,45),s.playerId+" — "+head,title);GUI.Label(new Rect(r.x+20,r.y+70,720,55),text,GUI.skin.label);for(int d=0;d<s.dice.Count;d++){if(!gm.IsDieAvailable(p,d))continue;Rect q=new Rect(r.x+25+d*105,r.y+135,90,70);GUI.enabled=CanChoose(p,d);if(GUI.Button(q,"Die "+(d+1),button))Die(d);GUI.enabled=true;DrawValue(q,p,d);}if(GUI.Button(new Rect(r.x+25,r.y+285,710,55),"BACK",button))BackDie();}
    void DrawValue(Rect q,int p,int d){string k=Key(p,d);GUIStyle st=value;if(modifierOriginal.ContainsKey(k))st=gm.Players[p].dice[d]>modifierOriginal[k]?green:red;GUI.Label(new Rect(q.x,q.y+35,q.width,30),gm.Players[p].dice[d].ToString(),st);}
    void Targets(string head,string text,bool self,bool ignore,Step back){Rect r=Box(850,370);GUI.Box(r,"",box);GUI.Label(new Rect(r.x+20,r.y+20,810,45),head,title);GUI.Label(new Rect(r.x+20,r.y+70,810,35),text,GUI.skin.label);float x=r.x+25;for(int i=0;i<gm.Players.Count;i++){if(!self&&i==pi)continue;GUI.enabled=ignore||CanPlayer(i);if(GUI.Button(new Rect(x,r.y+125,145,75),gm.Players[i].playerId+"\nChips: "+gm.Players[i].chips,button))Target(i);GUI.enabled=true;x+=160;}if(GUI.Button(new Rect(r.x+25,r.y+270,800,55),"BACK",button)){step=back;ti=si=-1;execMsg=null;}}
    void Pair(string head,string text,bool first){Rect r=Box(850,370);GUI.Box(r,"",box);GUI.Label(new Rect(r.x+20,r.y+20,810,45),head,title);GUI.Label(new Rect(r.x+20,r.y+70,810,35),text,GUI.skin.label);float x=r.x+25;for(int i=0;i<gm.Players.Count;i++){if(i==pi||(!first&&i==ti)||protectedPlayers.Contains(i))continue;if(GUI.Button(new Rect(x,r.y+125,145,75),gm.Players[i].playerId,button)){if(first){ti=i;step=Step.SpecialMirrorFirstDie;}else{si=i;step=Step.SpecialMirrorSecondDie;}}x+=160;}if(GUI.Button(new Rect(r.x+25,r.y+270,800,55),"BACK",button))step=Step.SpecialMirrorChoice;}
    void CollectorCards(){var p=gm.Players[ti];Rect r=Box(820,430);GUI.Box(r,"",box);GUI.Label(new Rect(r.x+20,r.y+20,780,45),"COLLECTOR — STEAL FROM "+p.playerId,title);for(int i=0;i<p.hand.cardsInHand.Count;i++)if(GUI.Button(new Rect(r.x+25+(i%5)*155,r.y+110+(i/5)*80,140,65),"CARD "+(i+1),button))Collector(p.hand.cardsInHand[i]);if(GUI.Button(new Rect(r.x+25,r.y+345,770,55),"BACK",button)){step=Step.CollectorTarget;ti=-1;}}
    void ModifierDirection(){Rect r=Box(700,360);GUI.Box(r,"",box);GUI.Label(new Rect(r.x+20,r.y+20,660,45),"MODIFIER",title);GUI.Label(new Rect(r.x+20,r.y+70,660,30),"Choose +1 or -1. You can still go back.",GUI.skin.label);if(GUI.Button(new Rect(r.x+50,r.y+125,280,70),"+1",button)){mod=1;step=Step.ModifierTarget;}if(GUI.Button(new Rect(r.x+370,r.y+125,280,70),"-1",button)){mod=-1;step=Step.ModifierTarget;}if(GUI.Button(new Rect(r.x+50,r.y+225,600,55),"BACK",button))BackCards();}
    void ModifierTarget(){Rect r=Box(900,520);GUI.Box(r,"",box);GUI.Label(new Rect(r.x+20,r.y+20,860,45),"MODIFIER "+(mod>0?"+1":"-1")+" — CHOOSE DIE",title);float y=r.y+105;for(int p=0;p<gm.Players.Count;p++){GUI.Label(new Rect(r.x+20,y,140,30),gm.Players[p].playerId,GUI.skin.label);float x=r.x+170;for(int d=0;d<gm.Players[p].dice.Count;d++){if(!gm.IsDieAvailable(p,d))continue;bool ok=(mod>0&&gm.Players[p].dice[d]<6)||(mod<0&&gm.Players[p].dice[d]>1);ok&=CanAffect(p,d);GUI.enabled=ok;Rect q=new Rect(x,y-5,90,60);if(GUI.Button(q,"Die "+(d+1),button))Modifier(p,d);GUI.enabled=true;DrawValue(q,p,d);x+=105;}y+=80;}if(GUI.Button(new Rect(r.x+20,r.y+455,860,50),"BACK",button))step=Step.ModifierDirection;}
    void Choice(string head,string[] opts,Action<int> pick,Step back){Rect r=Box(820,390);GUI.Box(r,"",box);GUI.Label(new Rect(r.x+20,r.y+20,780,45),head,title);for(int i=0;i<opts.Length;i++)if(GUI.Button(new Rect(r.x+35,r.y+90+i*75,750,60),opts[i],button))pick(i);if(GUI.Button(new Rect(r.x+35,r.y+250+opts.Length*10,750,55),"BACK",button))step=back;}
    void SpecialSoldierAll(){Rect r=Box(760,390);GUI.Box(r,"",box);GUI.Label(new Rect(r.x+20,r.y+20,720,45),"SPECIAL SOLDIER — CHOOSE DIE",title);for(int d=0;d<gm.RoundDiceCount;d++){bool ok=false;for(int p=0;p<gm.Players.Count;p++)if(p!=pi&&CanAffect(p,d))ok=true;GUI.enabled=ok;if(GUI.Button(new Rect(r.x+25+d*105,r.y+120,90,70),"Die "+(d+1),button)){for(int p=0;p<gm.Players.Count;p++)if(p!=pi&&CanAffect(p,d))gm.Players[p].dice[d]=UnityEngine.Random.Range(1,7);Commit();}GUI.enabled=true;}if(GUI.Button(new Rect(r.x+25,r.y+285,710,55),"BACK",button))step=Step.SpecialSoldierChoice;}
    void SpecialCollectorTake(){if(collectorPos>=collectorOpp.Count){step=Step.SpecialCollectorPlay;return;}int p=collectorOpp[collectorPos];Rect r=Box(820,400);GUI.Box(r,"",box);GUI.Label(new Rect(r.x+20,r.y+20,780,45),"SPECIAL COLLECTOR — TAKE FROM "+gm.Players[p].playerId,title);for(int i=0;i<gm.Players[p].hand.cardsInHand.Count;i++)if(GUI.Button(new Rect(r.x+25+i*155,r.y+125,140,65),"CARD "+(i+1),button))TakeCollector(i);if(GUI.Button(new Rect(r.x+25,r.y+285,770,55),"BACK",button))step=Step.SpecialCollectorChoice;}
    void SpecialCollectorPlay(){Rect r=Box(850,430);GUI.Box(r,"",box);GUI.Label(new Rect(r.x+20,r.y+20,810,45),"SPECIAL COLLECTOR — CHOOSE CARD TO PLAY",title);for(int i=0;i<collectorPool.Count;i++){var c=collectorPool[i];if(c!=null&&GUI.Button(new Rect(r.x+25+i*165,r.y+125,150,80),c.data.id+"\n"+c.data.cardType,button))PlayCollector(i);}if(GUI.Button(new Rect(r.x+25,r.y+330,800,55),"BACK",button))step=Step.SpecialCollectorTake;}
    void ExecutionerEffects(){Rect r=Box(820,420);GUI.Box(r,"",box);GUI.Label(new Rect(r.x+20,r.y+20,780,45),"EXECUTIONER — "+gm.Players[ti].playerId,title);GUI.Label(new Rect(r.x+20,r.y+70,780,35),"Choose the permanent effect to cancel.",GUI.skin.label);for(int i=0;i<execEffects.Count;i++)if(GUI.Button(new Rect(r.x+25,r.y+120+i*70,760,55),EffectText(execEffects[i]),button))CancelEffect(execEffects[i]);if(execEffects.Count==0)GUI.Label(new Rect(r.x+25,r.y+120,760,35),"No cancelable permanent effect.",GUI.skin.label);if(GUI.Button(new Rect(r.x+25,r.y+330,760,55),"BACK",button))step=Step.ExecutionerTarget;}

    void Select(CardInstance c){if(c==null||c.data==null)return;active=c;ti=si=di=-1;mod=0;execMsg=null;if(c.data.isBlankCard){Commit();return;}if(c.data.isModifier){step=Step.ModifierDirection;return;}if(c.data.rarity==CardRarity.Special){RouteSpecial(c.data.cardType);return;}if(c.data.rarity==CardRarity.Royalty){RouteRoyalty(c.data.cardType);return;}switch(c.data.cardType){case CardType.Artist:step=Step.ArtistDie;break;case CardType.Knight:step=Step.SoldierTarget;break;case CardType.Collector:step=Step.CollectorTarget;break;case CardType.Bodyguard:step=Step.BodyguardDie;break;case CardType.Mirror:step=Step.MirrorTarget;break;case CardType.Executioner:step=Step.ExecutionerTarget;break;default:Commit();break;}}
    void RouteSpecial(CardType t){switch(t){case CardType.Artist:step=Step.SpecialArtistChoice;break;case CardType.Knight:step=Step.SpecialSoldierChoice;break;case CardType.Collector:step=Step.SpecialCollectorChoice;break;case CardType.Bodyguard:step=Step.SpecialBodyguardChoice;break;case CardType.Mirror:step=Step.SpecialMirrorChoice;break;case CardType.Executioner:step=Step.SpecialExecutionerTarget;break;default:Commit();break;}}
    void RouteRoyalty(CardType t){switch(t){case CardType.Joker:step=Step.JokerTarget;break;case CardType.Queen:Queen();break;case CardType.King:King();break;case CardType.GordonRobleys:step=Step.GordonChoice;break;default:Commit();break;}}
    void Skip(){active=null;step=Step.DieAfterSkip;ti=si=di=-1;mod=0;}
    void BackCards(){active=null;ti=si=di=-1;mod=0;execMsg=null;collectorPool.Clear();collectorOpp.Clear();step=Step.Cards;}
    void BackDie(){switch(step){case Step.DieAfterSkip:case Step.ArtistDie:case Step.BodyguardDie:case Step.SpecialArtistDie:case Step.JokerDie:BackCards();break;case Step.SoldierDie:ti=-1;step=Step.SoldierTarget;break;case Step.MirrorOwnDie:ti=-1;step=Step.MirrorTarget;break;case Step.MirrorTargetDie:di=-1;step=Step.MirrorOwnDie;break;case Step.SpecialSoldierDie:ti=-1;step=Step.SpecialSoldierTarget;break;case Step.SpecialSoldierAllDie:step=Step.SpecialSoldierChoice;break;case Step.SpecialMirrorOwnDie:ti=-1;step=Step.SpecialMirrorTarget;break;case Step.SpecialMirrorTargetDie:di=-1;step=Step.SpecialMirrorOwnDie;break;case Step.SpecialMirrorFirstDie:ti=-1;di=-1;step=Step.SpecialMirrorFirstOpponent;break;case Step.SpecialMirrorSecondDie:si=-1;di=-1;step=Step.SpecialMirrorSecondOpponent;break;}}
    void Target(int t){ti=t;switch(step){case Step.SoldierTarget:step=Step.SoldierDie;break;case Step.CollectorTarget:step=Step.CollectorCard;break;case Step.MirrorTarget:step=Step.MirrorOwnDie;break;case Step.ExecutionerTarget:Executioner(t);break;case Step.SpecialSoldierTarget:SpecialSoldier(t);break;case Step.SpecialMirrorTarget:step=Step.SpecialMirrorOwnDie;break;case Step.SpecialExecutionerTarget:SpecialExecutioner(t);break;case Step.SpecialBodyguardTarget:SpecialBodyguardPlayer(t);break;case Step.JokerTarget:step=Step.JokerDie;break;}}
    void Die(int d){switch(step){case Step.DieAfterSkip:int p=pi;if(gm.TrySkipCardAction(p))gm.TryPlayDie(p,d);break;case Step.ArtistDie:Reroll(pi,d,1);Commit();break;case Step.SoldierDie:if(CanAffect(ti,d)){Reroll(ti,d,1);Commit();}break;case Step.BodyguardDie:NormalBodyguard(d);break;case Step.MirrorOwnDie:di=d;step=Step.MirrorTargetDie;break;case Step.MirrorTargetDie:if(CanAffect(ti,d)){Exchange(pi,di,ti,d);Commit();}break;case Step.SpecialArtistDie:Reroll(pi,d,3);Commit();break;case Step.SpecialSoldierDie:if(CanAffect(ti,d)){Reroll(ti,d,1);Commit();}break;case Step.SpecialMirrorOwnDie:di=d;step=Step.SpecialMirrorTargetDie;break;case Step.SpecialMirrorTargetDie:if(CanAffect(ti,d)){Exchange(pi,di,ti,d);Commit();}break;case Step.SpecialMirrorFirstDie:di=d;step=Step.SpecialMirrorSecondOpponent;break;case Step.SpecialMirrorSecondDie:if(CanAffect(si,d)){Exchange(ti,di,si,d);Commit();}break;case Step.JokerDie:if(CanAffect(ti,d)){gm.Players[ti].dice[d]=7-gm.Players[ti].dice[d];Commit();}break;}}
    void Reroll(int p,int d,int times){if(!CanAffect(p,d)&&!(p==pi&&(step==Step.ArtistDie||step==Step.SpecialArtistDie)))return;for(int i=0;i<times;i++)gm.Players[p].dice[d]=UnityEngine.Random.Range(1,7);}
    void Exchange(int a,int ad,int b,int bd){if(a<0||b<0||ad<0||bd<0)return;if(!gm.IsDieAvailable(a,ad)||!gm.IsDieAvailable(b,bd))return;int av=gm.Players[a].dice[ad];gm.Players[a].dice[ad]=gm.Players[b].dice[bd];gm.Players[b].dice[bd]=av;}
    void Collector(CardInstance c){if(c==null)return;gm.Players[ti].hand.RemoveCard(c);CommitCardOnly();active=c;RouteStolen(c);}
    void Modifier(int p,int d){if(!CanAffect(p,d))return;int v=gm.Players[p].dice[d];if(mod>0&&v>=6||mod<0&&v<=1)return;string k=Key(p,d);if(modifierOriginal.ContainsKey(k))return;modifierOriginal[k]=v;gm.Players[p].dice[d]=v+mod;Persistent(new Effect{type=EffectType.Modifier,card=active,owner=pi,target=p,die=d,key=k});}
    void NormalBodyguard(int d){string k=Key(pi,d);if(protectedDice.Contains(k))return;protectedDice.Add(k);Persistent(new Effect{type=EffectType.BodyguardDie,card=active,owner=pi,target=pi,die=d,key=k});}

    void Executioner(int t){if(!playedCard.Contains(t)){blocked.Add(t);Debug.Log("[Cardado] Executioner blocked "+gm.Players[t].playerId+" for this hand.");Commit();return;}execEffects.Clear();foreach(var e in effects)if(e.owner==t)execEffects.Add(e);if(execEffects.Count==0){execMsg=gm.Players[t].playerId+" already played a card and has no cancelable permanent effect.";step=Step.ExecutionerTarget;}else if(execEffects.Count==1)CancelEffect(execEffects[0]);else step=Step.ExecutionerEffects;}
    void CancelEffect(Effect e){if(e==null)return;switch(e.type){case EffectType.Modifier:if(modifierOriginal.ContainsKey(e.key)){int[] k=Parse(e.key);if(k[0]>=0&&gm.IsDieAvailable(k[0],k[1]))gm.Players[k[0]].dice[k[1]]=modifierOriginal[e.key];modifierOriginal.Remove(e.key);}break;case EffectType.BodyguardDie:protectedDice.Remove(e.key);break;case EffectType.SpecialBodyguardPlayer:protectedPlayers.Remove(e.target);break;case EffectType.SpecialBodyguardHand:handBodyguard=false;handBodyguardEffect=null;break;}RemoveEffectObj(e,true);Commit();}
    void ChooseSpecialArtist(int o){if(o==0)step=Step.SpecialArtistDie;else{for(int d=0;d<gm.Players[pi].dice.Count;d++)if(CanChoose(pi,d))gm.Players[pi].dice[d]=UnityEngine.Random.Range(1,7);Commit();}}
    void ChooseSpecialSoldier(int o){step=o==0?Step.SpecialSoldierTarget:Step.SpecialSoldierAllDie;}
    void SpecialSoldier(int t){if(!CanPlayer(t))return;for(int d=0;d<gm.Players[t].dice.Count;d++)if(CanAffect(t,d))gm.Players[t].dice[d]=UnityEngine.Random.Range(1,7);Commit();}
    void ChooseSpecialCollector(int o){if(o==1){CommitCardOnly();for(int i=0;i<3;i++){var c=gm.RoundDeck.Draw();if(c==null)break;gm.Players[pi].hand.AddCard(c);}After();return;}collectorPool.Clear();collectorOpp.Clear();collectorPos=0;for(int p=0;p<gm.Players.Count;p++)if(p!=pi&&gm.Players[p].hand.cardsInHand.Count>0&&CanPlayer(p))collectorOpp.Add(p);step=collectorOpp.Count==0?Step.SpecialCollectorPlay:Step.SpecialCollectorTake;}
    void TakeCollector(int i){int p=collectorOpp[collectorPos];if(i<0||i>=gm.Players[p].hand.cardsInHand.Count)return;var c=gm.Players[p].hand.cardsInHand[i];gm.Players[p].hand.RemoveCard(c);collectorPool.Add(c);collectorPos++;if(collectorPos>=collectorOpp.Count)step=Step.SpecialCollectorPlay;}
    void PlayCollector(int i){if(i<0||i>=collectorPool.Count)return;var c=collectorPool[i];for(int x=0;x<collectorPool.Count;x++)if(x!=i)gm.DiscardResolvedCard(collectorPool[x]);collectorPool.Clear();CommitCardOnly();active=c;RouteStolen(c);}
    void RouteStolen(CardInstance c){if(c==null||c.data==null)return;if(c.data.isBlankCard){gm.DiscardResolvedCard(c);After();return;}if(c.data.isModifier){step=Step.ModifierDirection;return;}if(c.data.rarity==CardRarity.Special){RouteSpecial(c.data.cardType);return;}if(c.data.rarity==CardRarity.Royalty){RouteRoyalty(c.data.cardType);return;}switch(c.data.cardType){case CardType.Artist:step=Step.ArtistDie;break;case CardType.Knight:step=Step.SoldierTarget;break;case CardType.Collector:step=Step.CollectorTarget;break;case CardType.Bodyguard:step=Step.BodyguardDie;break;case CardType.Mirror:step=Step.MirrorTarget;break;case CardType.Executioner:step=Step.ExecutionerTarget;break;default:gm.DiscardResolvedCard(c);After();break;}}
    void ChooseSpecialBodyguard(int o){if(o==0){step=Step.SpecialBodyguardTarget;return;}handBodyguard=true;handBodyguardEffect=new Effect{type=EffectType.SpecialBodyguardHand,card=active,owner=pi,key="special_bodyguard_hand"};effects.Add(handBodyguardEffect);CommitPersistentCard();After();}
    void SpecialBodyguardPlayer(int t){protectedPlayers.Add(t);var e=new Effect{type=EffectType.SpecialBodyguardPlayer,card=active,owner=pi,target=t,key="special_bodyguard_player:"+t};effects.Add(e);CommitPersistentCard();After();}
    void ChooseSpecialMirror(int o){step=o==0?Step.SpecialMirrorTarget:Step.SpecialMirrorFirstOpponent;}
    void SpecialExecutioner(int t){if(!CanTargetIgnore(t))return;var p=gm.Players[t];var cards=new List<CardInstance>(p.hand.cardsInHand);p.hand.cardsInHand.Clear();foreach(var c in cards)gm.DiscardResolvedCard(c);Commit();}
    void ChooseGordon(int o){step=o==0?Step.SpecialArtistChoice:o==1?Step.SpecialSoldierChoice:o==2?Step.SpecialCollectorChoice:Step.SpecialBodyguardChoice;}
    void Queen(){CommitCardOnly();for(int p=0;p<gm.Players.Count;p++){var cards=new List<CardInstance>(gm.Players[p].hand.cardsInHand);gm.Players[p].hand.cardsInHand.Clear();foreach(var c in cards)gm.DiscardResolvedCard(c);}for(int p=0;p<gm.Players.Count;p++)for(int i=0;i<3;i++){var c=gm.RoundDeck.Draw();if(c==null)break;gm.Players[p].hand.AddCard(c);}Another();}
    void King(){CommitCardOnly();for(int p=0;p<gm.Players.Count;p++)for(int d=0;d<gm.Players[p].dice.Count;d++)if(CanAffect(p,d))gm.Players[p].dice[d]=UnityEngine.Random.Range(1,7);Another();}

    void CommitPersistentCard(){if(active==null)return;active.isPlayed=true;gm.Players[pi].hand.RemoveCard(active);playedCard.Add(pi);active=null;}
    void Persistent(Effect e){if(e==null||active==null)return;e.card.isPlayed=true;gm.Players[pi].hand.RemoveCard(e.card);effects.Add(e);playedCard.Add(pi);active=null;After();}
    void CommitCardOnly(){if(active==null)return;active.isPlayed=true;gm.Players[pi].hand.RemoveCard(active);gm.DiscardResolvedCard(active);playedCard.Add(pi);}
    void Commit(){CommitCardOnly();After();}
    void After(){active=null;visible=false;step=Step.None;ti=si=di=-1;mod=0;execMsg=null;collectorOpp.Clear();collectorPool.Clear();gm.TrySkipCardAction(pi);}
    void Another(){active=null;ti=si=di=-1;execMsg=null;if(gm.Players[pi].hand.cardsInHand.Count>0){visible=true;step=Step.Cards;}else{visible=false;gm.TrySkipCardAction(pi);}}

    bool CanChoose(int p,int d){if(!gm.IsDieAvailable(p,d))return false;if(step==Step.DieAfterSkip)return p==pi;if(protectedPlayers.Contains(p))return false;return step==Step.ArtistDie||step==Step.SpecialArtistDie||step==Step.BodyguardDie||step==Step.MirrorOwnDie||step==Step.SpecialMirrorOwnDie?p==pi:CanAffect(p,d);}
    bool CanAffect(int p,int d)=>gm.IsDieAvailable(p,d)&&CanPlayer(p)&&!protectedDice.Contains(Key(p,d));
    bool CanPlayer(int p)=>p>=0&&p<gm.Players.Count&&!protectedPlayers.Contains(p);
    bool CanTargetIgnore(int p)=>p>=0&&p<gm.Players.Count&&p!=pi;
    string EffectText(Effect e){string owner=e.owner>=0&&e.owner<gm.Players.Count?gm.Players[e.owner].playerId:"?";switch(e.type){case EffectType.Modifier:return (e.card.data.canAdd?"+1":"-1")+" — "+owner+" → "+gm.Players[e.target].playerId+" Die "+(e.die+1);case EffectType.BodyguardDie:return "BODYGUARD — "+owner+" Die "+(e.die+1);case EffectType.SpecialBodyguardPlayer:return "SPECIAL BODYGUARD — "+owner+" protects "+gm.Players[e.target].playerId;default:return "SPECIAL BODYGUARD — "+owner+" protects all dice played this hand";}}
    void RemoveEffect(EffectType t,string k,bool discard){for(int i=effects.Count-1;i>=0;i--)if(effects[i].type==t&&effects[i].key==k){RemoveEffectObj(effects[i],discard);return;}}
    void RemoveEffectObj(Effect e,bool discard){if(e==null)return;effects.Remove(e);if(e.type==EffectType.SpecialBodyguardHand&&handBodyguardEffect==e){handBodyguard=false;handBodyguardEffect=null;}if(discard&&e.card!=null)gm.DiscardResolvedCard(e.card);}
    int[] Parse(string k){var a=k.Split(':');int p,d;if(a.Length!=2||!int.TryParse(a[0],out p)||!int.TryParse(a[1],out d))return new[]{-1,-1};return new[]{p,d};}
    string Key(int p,int d)=>p+":"+d;int Index(CardadoPlayerState p){for(int i=0;i<gm.Players.Count;i++)if(gm.Players[i]==p)return i;return -1;}Rect Box(float w,float h)=>new Rect((Screen.width-w)/2f,(Screen.height-h)/2f,w,h);
    void Styles(){if(box!=null)return;box=new GUIStyle(GUI.skin.box){padding=new RectOffset(20,20,20,20)};title=new GUIStyle(GUI.skin.label){fontSize=24,fontStyle=FontStyle.Bold,alignment=TextAnchor.MiddleCenter};button=new GUIStyle(GUI.skin.button){fontSize=18,fontStyle=FontStyle.Bold};value=new GUIStyle(GUI.skin.label){fontSize=20,fontStyle=FontStyle.Bold,alignment=TextAnchor.MiddleCenter};green=new GUIStyle(value);green.normal.textColor=Color.green;red=new GUIStyle(value);red.normal.textColor=Color.red;small=new GUIStyle(GUI.skin.label){fontSize=14,fontStyle=FontStyle.Bold};}
}